--
-- PostgreSQL database dump
--

\restrict 8VP4XK4NmuDHBBOD8vtZ0y4pPj9e4TRBL3CBiWiLd6rGbbLgKXZiAGDLxF6ZJ94

-- Dumped from database version 18.4 (Debian 18.4-1.pgdg12+1)
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: coworkspace_user
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO coworkspace_user;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: coworkspace_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO coworkspace_user;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: coworkspace_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: coworkspace_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO coworkspace_user;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: coworkspace_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: coworkspace_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO coworkspace_user;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: coworkspace_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: coworkspace_user
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO coworkspace_user;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: coworkspace_user
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO coworkspace_user;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: coworkspace_user
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: coworkspace_user
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: coworkspace_user
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO coworkspace_user;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: coworkspace_user
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: coworkspace_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO coworkspace_user;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: coworkspace_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: coworkspace_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO coworkspace_user;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: coworkspace_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: coworkspace_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO coworkspace_user;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: coworkspace_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: coworkspace_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO coworkspace_user;

--
-- Name: reservas_empresacliente; Type: TABLE; Schema: public; Owner: coworkspace_user
--

CREATE TABLE public.reservas_empresacliente (
    id integer NOT NULL,
    nombre character varying(200) NOT NULL,
    ruc character varying(13) NOT NULL,
    telefono character varying(15) NOT NULL,
    email character varying(254) NOT NULL,
    direccion text NOT NULL,
    logo character varying(100),
    fecha_registro date NOT NULL,
    plan character varying(20) NOT NULL,
    activo boolean NOT NULL
);


ALTER TABLE public.reservas_empresacliente OWNER TO coworkspace_user;

--
-- Name: reservas_empresacliente_id_seq; Type: SEQUENCE; Schema: public; Owner: coworkspace_user
--

ALTER TABLE public.reservas_empresacliente ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservas_empresacliente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservas_escritoriodedicado; Type: TABLE; Schema: public; Owner: coworkspace_user
--

CREATE TABLE public.reservas_escritoriodedicado (
    id integer NOT NULL,
    codigo character varying(20) NOT NULL,
    piso integer NOT NULL,
    precio_mensual numeric(8,2) NOT NULL,
    tipo character varying(20) NOT NULL,
    estado character varying(20) NOT NULL,
    miembro_asignado_id integer,
    posicion integer NOT NULL,
    CONSTRAINT reservas_escritoriodedicado_piso_check CHECK ((piso >= 0)),
    CONSTRAINT reservas_escritoriodedicado_posicion_check CHECK ((posicion >= 0))
);


ALTER TABLE public.reservas_escritoriodedicado OWNER TO coworkspace_user;

--
-- Name: reservas_escritoriodedicado_id_seq; Type: SEQUENCE; Schema: public; Owner: coworkspace_user
--

ALTER TABLE public.reservas_escritoriodedicado ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservas_escritoriodedicado_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservas_evento; Type: TABLE; Schema: public; Owner: coworkspace_user
--

CREATE TABLE public.reservas_evento (
    id integer NOT NULL,
    titulo character varying(200) NOT NULL,
    descripcion text NOT NULL,
    fecha_evento date NOT NULL,
    hora_inicio time without time zone NOT NULL,
    hora_fin time without time zone NOT NULL,
    capacidad_maxima integer NOT NULL,
    foto character varying(100),
    tipo_evento character varying(20) NOT NULL,
    publico boolean NOT NULL,
    organizador_id integer NOT NULL,
    sala_id integer,
    CONSTRAINT reservas_evento_capacidad_maxima_check CHECK ((capacidad_maxima >= 0))
);


ALTER TABLE public.reservas_evento OWNER TO coworkspace_user;

--
-- Name: reservas_evento_id_seq; Type: SEQUENCE; Schema: public; Owner: coworkspace_user
--

ALTER TABLE public.reservas_evento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservas_evento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservas_factura; Type: TABLE; Schema: public; Owner: coworkspace_user
--

CREATE TABLE public.reservas_factura (
    id integer NOT NULL,
    numero_factura character varying(20) NOT NULL,
    fecha_emision date NOT NULL,
    fecha_vencimiento date NOT NULL,
    subtotal numeric(10,2) NOT NULL,
    iva numeric(10,2) NOT NULL,
    total numeric(10,2) NOT NULL,
    pdf character varying(100),
    estado character varying(20) NOT NULL,
    tipo_factura character varying(20) NOT NULL,
    notas text,
    empresa_id integer NOT NULL
);


ALTER TABLE public.reservas_factura OWNER TO coworkspace_user;

--
-- Name: reservas_factura_id_seq; Type: SEQUENCE; Schema: public; Owner: coworkspace_user
--

ALTER TABLE public.reservas_factura ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservas_factura_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservas_miembro; Type: TABLE; Schema: public; Owner: coworkspace_user
--

CREATE TABLE public.reservas_miembro (
    id integer NOT NULL,
    cedula character varying(10) NOT NULL,
    nombre character varying(100) NOT NULL,
    apellido character varying(100) NOT NULL,
    email character varying(254) NOT NULL,
    telefono character varying(15) NOT NULL,
    foto character varying(100),
    cargo character varying(20) NOT NULL,
    fecha_ingreso date NOT NULL,
    activo boolean NOT NULL,
    empresa_id integer NOT NULL,
    usuario_id integer
);


ALTER TABLE public.reservas_miembro OWNER TO coworkspace_user;

--
-- Name: reservas_miembro_id_seq; Type: SEQUENCE; Schema: public; Owner: coworkspace_user
--

ALTER TABLE public.reservas_miembro ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservas_miembro_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservas_reservasala; Type: TABLE; Schema: public; Owner: coworkspace_user
--

CREATE TABLE public.reservas_reservasala (
    id integer NOT NULL,
    fecha date NOT NULL,
    hora_inicio time without time zone NOT NULL,
    hora_fin time without time zone NOT NULL,
    proposito character varying(200) NOT NULL,
    numero_asistentes integer NOT NULL,
    estado character varying(20) NOT NULL,
    costo_total numeric(8,2) NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    miembro_id integer NOT NULL,
    sala_id integer NOT NULL,
    CONSTRAINT reservas_reservasala_numero_asistentes_check CHECK ((numero_asistentes >= 0))
);


ALTER TABLE public.reservas_reservasala OWNER TO coworkspace_user;

--
-- Name: reservas_reservasala_id_seq; Type: SEQUENCE; Schema: public; Owner: coworkspace_user
--

ALTER TABLE public.reservas_reservasala ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservas_reservasala_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservas_salareunion; Type: TABLE; Schema: public; Owner: coworkspace_user
--

CREATE TABLE public.reservas_salareunion (
    id integer NOT NULL,
    nombre character varying(100) NOT NULL,
    capacidad integer NOT NULL,
    metros_cuadrados numeric(6,2) NOT NULL,
    piso integer NOT NULL,
    foto character varying(100),
    precio_hora numeric(8,2) NOT NULL,
    equipamiento character varying(20) NOT NULL,
    activo boolean NOT NULL,
    CONSTRAINT reservas_salareunion_capacidad_check CHECK ((capacidad >= 0)),
    CONSTRAINT reservas_salareunion_piso_check CHECK ((piso >= 0))
);


ALTER TABLE public.reservas_salareunion OWNER TO coworkspace_user;

--
-- Name: reservas_salareunion_id_seq; Type: SEQUENCE; Schema: public; Owner: coworkspace_user
--

ALTER TABLE public.reservas_salareunion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservas_salareunion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: coworkspace_user
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: coworkspace_user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: coworkspace_user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add empresa cliente	7	add_empresacliente
26	Can change empresa cliente	7	change_empresacliente
27	Can delete empresa cliente	7	delete_empresacliente
28	Can view empresa cliente	7	view_empresacliente
29	Can add sala reunion	8	add_salareunion
30	Can change sala reunion	8	change_salareunion
31	Can delete sala reunion	8	delete_salareunion
32	Can view sala reunion	8	view_salareunion
33	Can add factura	9	add_factura
34	Can change factura	9	change_factura
35	Can delete factura	9	delete_factura
36	Can view factura	9	view_factura
37	Can add miembro	10	add_miembro
38	Can change miembro	10	change_miembro
39	Can delete miembro	10	delete_miembro
40	Can view miembro	10	view_miembro
41	Can add escritorio dedicado	11	add_escritoriodedicado
42	Can change escritorio dedicado	11	change_escritoriodedicado
43	Can delete escritorio dedicado	11	delete_escritoriodedicado
44	Can view escritorio dedicado	11	view_escritoriodedicado
45	Can add reserva sala	12	add_reservasala
46	Can change reserva sala	12	change_reservasala
47	Can delete reserva sala	12	delete_reservasala
48	Can view reserva sala	12	view_reservasala
49	Can add evento	13	add_evento
50	Can change evento	13	change_evento
51	Can delete evento	13	delete_evento
52	Can view evento	13	view_evento
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: coworkspace_user
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
2	pbkdf2_sha256$1000000$PkNbZQ3NqlqC13usTw8631$DuafrwWDGmd3CCxSdJefCul8g1wTbXEbEsj3zQWduuc=	2026-08-05 18:22:51.537024+00	f	ricardo			ricardosacatoro123@gmail.com	f	t	2026-08-05 18:19:56.63446+00
3	pbkdf2_sha256$1000000$n6VFVSGcjKDQoKsAQKR16S$PGHX4G2D33EHt7W0pATkKVJUL410DMg2wHlm00ADYCI=	2026-08-05 19:10:08.063033+00	f	kelly			kelly.chicaiza5049@utc.edu.ec	f	t	2026-08-05 19:10:06.127183+00
1	pbkdf2_sha256$1000000$W9khhnECpeH1lKyFfkz9eO$XJrhLjqDEQLgyGu8Km7H26bh86G0Xp+KoseEnesOmjc=	2026-08-05 19:33:11.169552+00	t	admin			admin@coworkspace.com	t	t	2026-07-30 04:49:50.298161+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: coworkspace_user
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: coworkspace_user
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: coworkspace_user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: coworkspace_user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	reservas	empresacliente
8	reservas	salareunion
9	reservas	factura
10	reservas	miembro
11	reservas	escritoriodedicado
12	reservas	reservasala
13	reservas	evento
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: coworkspace_user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-07-30 04:48:07.224876+00
2	auth	0001_initial	2026-07-30 04:48:08.133603+00
3	admin	0001_initial	2026-07-30 04:48:08.241268+00
4	admin	0002_logentry_remove_auto_add	2026-07-30 04:48:08.246263+00
5	admin	0003_logentry_add_action_flag_choices	2026-07-30 04:48:08.253428+00
6	contenttypes	0002_remove_content_type_name	2026-07-30 04:48:08.26626+00
7	auth	0002_alter_permission_name_max_length	2026-07-30 04:48:08.277303+00
8	auth	0003_alter_user_email_max_length	2026-07-30 04:48:08.323584+00
9	auth	0004_alter_user_username_opts	2026-07-30 04:48:08.32938+00
10	auth	0005_alter_user_last_login_null	2026-07-30 04:48:08.337658+00
11	auth	0006_require_contenttypes_0002	2026-07-30 04:48:08.340717+00
12	auth	0007_alter_validators_add_error_messages	2026-07-30 04:48:08.346972+00
13	auth	0008_alter_user_username_max_length	2026-07-30 04:48:08.360358+00
14	auth	0009_alter_user_last_name_max_length	2026-07-30 04:48:08.367971+00
15	auth	0010_alter_group_name_max_length	2026-07-30 04:48:08.376133+00
16	auth	0011_update_proxy_permissions	2026-07-30 04:48:08.381443+00
17	auth	0012_alter_user_first_name_max_length	2026-07-30 04:48:08.392402+00
18	reservas	0001_initial	2026-07-30 04:48:08.643967+00
19	reservas	0002_alter_escritoriodedicado_posicion_x_and_more	2026-07-30 04:48:08.747523+00
20	reservas	0003_alter_escritoriodedicado_posicion_fields_unique	2026-07-30 04:48:08.765963+00
21	reservas	0004_cambiar_a_posicion_horizontal	2026-07-30 04:48:08.86136+00
22	sessions	0001_initial	2026-07-30 04:49:49.927883+00
23	reservas	0004_add_posicion_field	2026-08-05 13:28:22.332146+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: coworkspace_user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
0u36a6s5nxn2qjevk0v94o4dsc251q4s	.eJxVjEEOwiAQRe_C2hAoAwGX7j0DGYZBqgaS0q6Md9cmXej2v_f-S0Tc1hq3wUucszgLLU6_W0J6cNtBvmO7dUm9rcuc5K7Igw557Zmfl8P9O6g46rcugSFgCYq8BpgYWGeDvqhUXHIGknUMxB40okVFoDh4a1kZNRUqJN4f8xU4XA:1wpIyv:AY9c7eAfPl4mPHnfk0B_PtxWP6jr_e2rLQCjRhdsiBI	2026-08-13 05:06:57.35225+00
ucgvcl7frrshvioc4oaqw4mon9daa9sj	.eJxVjEEOwiAQRe_C2hAoAwGX7j0DGYZBqgaS0q6Md9cmXej2v_f-S0Tc1hq3wUucszgLLU6_W0J6cNtBvmO7dUm9rcuc5K7Igw557Zmfl8P9O6g46rcugSFgCYq8BpgYWGeDvqhUXHIGknUMxB40okVFoDh4a1kZNRUqJN4f8xU4XA:1wpJ02:_NIiM0AX_dzWL_kOM0ZzyLHh8R_18d-nlJtz9uq3ia0	2026-08-13 05:08:06.978637+00
j1r4j25vdtdsf0uygs8zowj5775dfqks	.eJxVjEEOwiAQRe_C2hAoAwGX7j0DGYZBqgaS0q6Md9cmXej2v_f-S0Tc1hq3wUucszgLLU6_W0J6cNtBvmO7dUm9rcuc5K7Igw557Zmfl8P9O6g46rcugSFgCYq8BpgYWGeDvqhUXHIGknUMxB40okVFoDh4a1kZNRUqJN4f8xU4XA:1wrgHK:RwiZrC25JEW-XYEj2r-1hPbI1lEoPubrSrSpMWudRfE	2026-08-19 18:23:46.745108+00
sjgrql94d2t5lsjxk8rxi77y8y562bgj	.eJxVjEEOwiAQRe_C2hAoAwGX7j0DGYZBqgaS0q6Md9cmXej2v_f-S0Tc1hq3wUucszgLLU6_W0J6cNtBvmO7dUm9rcuc5K7Igw557Zmfl8P9O6g46rcugSFgCYq8BpgYWGeDvqhUXHIGknUMxB40okVFoDh4a1kZNRUqJN4f8xU4XA:1wrh8E:M77PzmQoSGiG0hqgxpJ7RXV3IjH7Rgnqo0HRIJaanZE	2026-08-19 19:18:26.96886+00
8my7cxigvgyjdnk3dsrxwobc80n6or3s	.eJxVjEEOwiAQRe_C2hAoAwGX7j0DGYZBqgaS0q6Md9cmXej2v_f-S0Tc1hq3wUucszgLLU6_W0J6cNtBvmO7dUm9rcuc5K7Igw557Zmfl8P9O6g46rcugSFgCYq8BpgYWGeDvqhUXHIGknUMxB40okVFoDh4a1kZNRUqJN4f8xU4XA:1wrhMV:mxFRsr1pPVyc4XC9jCePmez8p7FgiquxUyp_EzBHrf0	2026-08-19 19:33:11.172535+00
\.


--
-- Data for Name: reservas_empresacliente; Type: TABLE DATA; Schema: public; Owner: coworkspace_user
--

COPY public.reservas_empresacliente (id, nombre, ruc, telefono, email, direccion, logo, fecha_registro, plan, activo) FROM stdin;
2	TechSolutions Cía. Ltda.	1792345678001	0987654321	kelly.chicaiza5049@utc.edu.ec	Av. Eloy Alfaro y Amazonas, Edificio Torre Central, Piso 5, Latacunga	logos_empresas/1b7c8036-d1ee-4c54-9550-bffa8257fa84.png	2026-08-05	empresarial	t
3	Marketing Digital Pro	1791234567001	0998765432	dayanak701@gmail.com	Calle Quito 45-23 y Guayaquil, Latacunga	logos_empresas/images.png	2026-08-05	profesional	t
4	EcoVerde S.A	1790987654001	0987754138	kelly.chicaiza5049@utc.edu.ec	Av. Unidad Nacional Km 2, Parque Empresarial, Latacunga	logos_empresas/png-clipart-logo-company-graphic-designer-design-company-logo.png	2026-08-05	basico	t
5	Empres	4561234565121	09562356482	ricardosacatoro123@gmail.com	Hola		2026-08-05	basico	t
\.


--
-- Data for Name: reservas_escritoriodedicado; Type: TABLE DATA; Schema: public; Owner: coworkspace_user
--

COPY public.reservas_escritoriodedicado (id, codigo, piso, precio_mensual, tipo, estado, miembro_asignado_id, posicion) FROM stdin;
1	ESC-101	1	100.00	individual	ocupado	3	1
5	ESC-107	1	45.00	individual	ocupado	2	5
2	ESC-102	1	50.00	privado	ocupado	3	3
3	ESC-103	1	100.00	compartido	disponible	\N	2
6	ESC-111	1	150.00	individual	disponible	1	4
4	ESC-104	1	54.00	individual	ocupado	1	7
\.


--
-- Data for Name: reservas_evento; Type: TABLE DATA; Schema: public; Owner: coworkspace_user
--

COPY public.reservas_evento (id, titulo, descripcion, fecha_evento, hora_inicio, hora_fin, capacidad_maxima, foto, tipo_evento, publico, organizador_id, sala_id) FROM stdin;
1	Networking Night: Conecta con Emprendedores	Noche de networking para conocer a otros emprendedores del coworking, compartir experiencias y crear alianzas estratégicas. Incluye snacks y bebidas.	2026-08-23	10:00:00	13:00:00	14	eventos/images_5.jpg	networking	t	2	2
3	Marketing Digital 2026	Taller práctico sobre las últimas tendencias en marketing digital, redes sociales y SEO. Incluye certificado de participación.\r\nOrganizador: Marketing Digital Pro	2026-08-23	08:00:00	09:00:00	15	eventos/images_6.jpg	capacitacion	t	3	2
4	Conferencia: Sostenibilidad Empresarial	Conferencia sobre cómo implementar prácticas sostenibles en empresas, con casos de éxito reales. Expositor internacional.\r\nOrganizador: EcoVerde S.A.	2026-08-14	10:00:00	14:00:00	8	eventos/images_5.jpg	conferencia	t	4	1
\.


--
-- Data for Name: reservas_factura; Type: TABLE DATA; Schema: public; Owner: coworkspace_user
--

COPY public.reservas_factura (id, numero_factura, fecha_emision, fecha_vencimiento, subtotal, iva, total, pdf, estado, tipo_factura, notas, empresa_id) FROM stdin;
1	FAC-000001	2026-08-05	2026-09-04	135.00	20.25	155.25	facturas/GUIA_PRACTICA_PASO_A_PASO_1.pdf	pagada	mensual	graciasssss	2
2	FAC-000002	2026-08-05	2026-09-04	195.00	29.25	224.25	facturas/Link_de_acceso_a_miro.pdf	pendiente	mensual	pagueeee	3
3	FAC-000003	2026-08-05	2026-09-18	984.00	147.60	1131.60	facturas/GUIA_PRACTICA_PASO_A_PASO_1_gyB1An4.pdf	pendiente	mensual	solicitamos que pague 	4
4	FAC-000004	2026-08-05	2026-09-04	1000.00	150.00	1150.00	facturas/Agentes__Helpdesk_TI.pdf	pagada	reservas	Nada	5
\.


--
-- Data for Name: reservas_miembro; Type: TABLE DATA; Schema: public; Owner: coworkspace_user
--

COPY public.reservas_miembro (id, cedula, nombre, apellido, email, telefono, foto, cargo, fecha_ingreso, activo, empresa_id, usuario_id) FROM stdin;
1	1750123456	Carlos Andrés 	Morales Vega	kelly.chicaiza5049@utc.edu.ec	0987654321	fotos_miembros/png-clipart-graphy-people-gesture-microphone-black-hair.png	gerente	2026-08-19	t	4	\N
2	1750234567	María Fernanda 	López García	kelly.chicaiza5049@utc.edu.ec	0987754138	fotos_miembros/png-clipart-graphy-people-gesture-microphone-black-hair.png	empleado	2026-08-03	t	4	\N
3	0504865049	Juan Pablo 	Sánchez Torres	kelly.chicaiza5049@utc.edu.ec	0987754138	fotos_miembros/images_1.jpg	empleado	2026-08-20	t	3	\N
4	1750456789	Ana Cristina 	Romero Flores	kelly.chicaiza5049@utc.edu.ec	0987754138	fotos_miembros/png-clipart-graphy-people-gesture-microphone-black-hair.png	freelancer	2026-08-20	t	2	\N
5	0550145454	Ricardo	Sacatoro	ricardosacatoro123@gmail.com	0986015956		gerente	2026-08-05	t	2	2
6	0504865049	KELLY	YANEZ	kelly.chicaiza5049@utc.edu.ec	0987754138		empleado	2026-08-05	t	2	3
\.


--
-- Data for Name: reservas_reservasala; Type: TABLE DATA; Schema: public; Owner: coworkspace_user
--

COPY public.reservas_reservasala (id, fecha, hora_inicio, hora_fin, proposito, numero_asistentes, estado, costo_total, fecha_creacion, miembro_id, sala_id) FROM stdin;
2	2026-08-05	08:00:00	11:00:00	Sesión de brainstorming con cliente	7	confirmada	90.00	2026-08-05 13:21:18.802497+00	2	1
6	2026-08-05	12:00:00	21:00:00	Sesión de brainstorming con cliente	10	confirmada	405.00	2026-08-05 13:48:11.464162+00	2	2
8	2026-08-07	07:00:00	13:00:00	Presentación de propuesta de diseño	8	confirmada	270.00	2026-08-05 13:50:50.114775+00	2	2
9	2026-08-05	14:00:00	17:00:00	Presentación de propuesta de diseño	7	pendiente	90.00	2026-08-05 13:52:12.740867+00	4	1
\.


--
-- Data for Name: reservas_salareunion; Type: TABLE DATA; Schema: public; Owner: coworkspace_user
--

COPY public.reservas_salareunion (id, nombre, capacidad, metros_cuadrados, piso, foto, precio_hora, equipamiento, activo) FROM stdin;
1	Sala Innovación	8	25.50	1	salas/images_3.jpg	30.00	premium	t
2	Sala Ejecutiva	15	35.00	2	salas/images_4.jpg	45.00	ejecutivo	t
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: coworkspace_user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: coworkspace_user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: coworkspace_user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 52, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: coworkspace_user
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: coworkspace_user
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 3, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: coworkspace_user
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: coworkspace_user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: coworkspace_user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 13, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: coworkspace_user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 23, true);


--
-- Name: reservas_empresacliente_id_seq; Type: SEQUENCE SET; Schema: public; Owner: coworkspace_user
--

SELECT pg_catalog.setval('public.reservas_empresacliente_id_seq', 5, true);


--
-- Name: reservas_escritoriodedicado_id_seq; Type: SEQUENCE SET; Schema: public; Owner: coworkspace_user
--

SELECT pg_catalog.setval('public.reservas_escritoriodedicado_id_seq', 6, true);


--
-- Name: reservas_evento_id_seq; Type: SEQUENCE SET; Schema: public; Owner: coworkspace_user
--

SELECT pg_catalog.setval('public.reservas_evento_id_seq', 4, true);


--
-- Name: reservas_factura_id_seq; Type: SEQUENCE SET; Schema: public; Owner: coworkspace_user
--

SELECT pg_catalog.setval('public.reservas_factura_id_seq', 4, true);


--
-- Name: reservas_miembro_id_seq; Type: SEQUENCE SET; Schema: public; Owner: coworkspace_user
--

SELECT pg_catalog.setval('public.reservas_miembro_id_seq', 6, true);


--
-- Name: reservas_reservasala_id_seq; Type: SEQUENCE SET; Schema: public; Owner: coworkspace_user
--

SELECT pg_catalog.setval('public.reservas_reservasala_id_seq', 9, true);


--
-- Name: reservas_salareunion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: coworkspace_user
--

SELECT pg_catalog.setval('public.reservas_salareunion_id_seq', 2, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: reservas_empresacliente reservas_empresacliente_pkey; Type: CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.reservas_empresacliente
    ADD CONSTRAINT reservas_empresacliente_pkey PRIMARY KEY (id);


--
-- Name: reservas_escritoriodedicado reservas_escritoriod_piso_posicion_uniq; Type: CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.reservas_escritoriodedicado
    ADD CONSTRAINT reservas_escritoriod_piso_posicion_uniq UNIQUE (piso, posicion);


--
-- Name: reservas_escritoriodedicado reservas_escritoriodedicado_codigo_key; Type: CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.reservas_escritoriodedicado
    ADD CONSTRAINT reservas_escritoriodedicado_codigo_key UNIQUE (codigo);


--
-- Name: reservas_escritoriodedicado reservas_escritoriodedicado_piso_posicion_024b1873_uniq; Type: CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.reservas_escritoriodedicado
    ADD CONSTRAINT reservas_escritoriodedicado_piso_posicion_024b1873_uniq UNIQUE (piso, posicion);


--
-- Name: reservas_escritoriodedicado reservas_escritoriodedicado_pkey; Type: CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.reservas_escritoriodedicado
    ADD CONSTRAINT reservas_escritoriodedicado_pkey PRIMARY KEY (id);


--
-- Name: reservas_evento reservas_evento_pkey; Type: CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.reservas_evento
    ADD CONSTRAINT reservas_evento_pkey PRIMARY KEY (id);


--
-- Name: reservas_factura reservas_factura_numero_factura_key; Type: CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.reservas_factura
    ADD CONSTRAINT reservas_factura_numero_factura_key UNIQUE (numero_factura);


--
-- Name: reservas_factura reservas_factura_pkey; Type: CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.reservas_factura
    ADD CONSTRAINT reservas_factura_pkey PRIMARY KEY (id);


--
-- Name: reservas_miembro reservas_miembro_pkey; Type: CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.reservas_miembro
    ADD CONSTRAINT reservas_miembro_pkey PRIMARY KEY (id);


--
-- Name: reservas_miembro reservas_miembro_usuario_id_key; Type: CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.reservas_miembro
    ADD CONSTRAINT reservas_miembro_usuario_id_key UNIQUE (usuario_id);


--
-- Name: reservas_reservasala reservas_reservasala_pkey; Type: CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.reservas_reservasala
    ADD CONSTRAINT reservas_reservasala_pkey PRIMARY KEY (id);


--
-- Name: reservas_salareunion reservas_salareunion_pkey; Type: CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.reservas_salareunion
    ADD CONSTRAINT reservas_salareunion_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: coworkspace_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: coworkspace_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: coworkspace_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: coworkspace_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: coworkspace_user
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: coworkspace_user
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: coworkspace_user
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: coworkspace_user
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: coworkspace_user
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: coworkspace_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: coworkspace_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: coworkspace_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: coworkspace_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: reservas_escritoriodedicado_codigo_3a6ad12f_like; Type: INDEX; Schema: public; Owner: coworkspace_user
--

CREATE INDEX reservas_escritoriodedicado_codigo_3a6ad12f_like ON public.reservas_escritoriodedicado USING btree (codigo varchar_pattern_ops);


--
-- Name: reservas_escritoriodedicado_miembro_asignado_id_f5a6e745; Type: INDEX; Schema: public; Owner: coworkspace_user
--

CREATE INDEX reservas_escritoriodedicado_miembro_asignado_id_f5a6e745 ON public.reservas_escritoriodedicado USING btree (miembro_asignado_id);


--
-- Name: reservas_evento_organizador_id_618d86ed; Type: INDEX; Schema: public; Owner: coworkspace_user
--

CREATE INDEX reservas_evento_organizador_id_618d86ed ON public.reservas_evento USING btree (organizador_id);


--
-- Name: reservas_evento_sala_id_c87ff737; Type: INDEX; Schema: public; Owner: coworkspace_user
--

CREATE INDEX reservas_evento_sala_id_c87ff737 ON public.reservas_evento USING btree (sala_id);


--
-- Name: reservas_factura_empresa_id_7673c15c; Type: INDEX; Schema: public; Owner: coworkspace_user
--

CREATE INDEX reservas_factura_empresa_id_7673c15c ON public.reservas_factura USING btree (empresa_id);


--
-- Name: reservas_factura_numero_factura_e8156b06_like; Type: INDEX; Schema: public; Owner: coworkspace_user
--

CREATE INDEX reservas_factura_numero_factura_e8156b06_like ON public.reservas_factura USING btree (numero_factura varchar_pattern_ops);


--
-- Name: reservas_miembro_empresa_id_4e317575; Type: INDEX; Schema: public; Owner: coworkspace_user
--

CREATE INDEX reservas_miembro_empresa_id_4e317575 ON public.reservas_miembro USING btree (empresa_id);


--
-- Name: reservas_reservasala_miembro_id_6fb6ef8f; Type: INDEX; Schema: public; Owner: coworkspace_user
--

CREATE INDEX reservas_reservasala_miembro_id_6fb6ef8f ON public.reservas_reservasala USING btree (miembro_id);


--
-- Name: reservas_reservasala_sala_id_6fc6572d; Type: INDEX; Schema: public; Owner: coworkspace_user
--

CREATE INDEX reservas_reservasala_sala_id_6fc6572d ON public.reservas_reservasala USING btree (sala_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reservas_escritoriodedicado reservas_escritoriod_miembro_asignado_id_f5a6e745_fk_reservas_; Type: FK CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.reservas_escritoriodedicado
    ADD CONSTRAINT reservas_escritoriod_miembro_asignado_id_f5a6e745_fk_reservas_ FOREIGN KEY (miembro_asignado_id) REFERENCES public.reservas_miembro(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reservas_evento reservas_evento_organizador_id_618d86ed_fk_reservas_; Type: FK CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.reservas_evento
    ADD CONSTRAINT reservas_evento_organizador_id_618d86ed_fk_reservas_ FOREIGN KEY (organizador_id) REFERENCES public.reservas_empresacliente(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reservas_evento reservas_evento_sala_id_c87ff737_fk_reservas_salareunion_id; Type: FK CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.reservas_evento
    ADD CONSTRAINT reservas_evento_sala_id_c87ff737_fk_reservas_salareunion_id FOREIGN KEY (sala_id) REFERENCES public.reservas_salareunion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reservas_factura reservas_factura_empresa_id_7673c15c_fk_reservas_; Type: FK CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.reservas_factura
    ADD CONSTRAINT reservas_factura_empresa_id_7673c15c_fk_reservas_ FOREIGN KEY (empresa_id) REFERENCES public.reservas_empresacliente(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reservas_miembro reservas_miembro_empresa_id_4e317575_fk_reservas_; Type: FK CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.reservas_miembro
    ADD CONSTRAINT reservas_miembro_empresa_id_4e317575_fk_reservas_ FOREIGN KEY (empresa_id) REFERENCES public.reservas_empresacliente(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reservas_miembro reservas_miembro_usuario_id_028ed20c_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.reservas_miembro
    ADD CONSTRAINT reservas_miembro_usuario_id_028ed20c_fk_auth_user_id FOREIGN KEY (usuario_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reservas_reservasala reservas_reservasala_miembro_id_6fb6ef8f_fk_reservas_miembro_id; Type: FK CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.reservas_reservasala
    ADD CONSTRAINT reservas_reservasala_miembro_id_6fb6ef8f_fk_reservas_miembro_id FOREIGN KEY (miembro_id) REFERENCES public.reservas_miembro(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reservas_reservasala reservas_reservasala_sala_id_6fc6572d_fk_reservas_; Type: FK CONSTRAINT; Schema: public; Owner: coworkspace_user
--

ALTER TABLE ONLY public.reservas_reservasala
    ADD CONSTRAINT reservas_reservasala_sala_id_6fc6572d_fk_reservas_ FOREIGN KEY (sala_id) REFERENCES public.reservas_salareunion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON SEQUENCES TO coworkspace_user;


--
-- Name: DEFAULT PRIVILEGES FOR TYPES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON TYPES TO coworkspace_user;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON FUNCTIONS TO coworkspace_user;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON TABLES TO coworkspace_user;


--
-- PostgreSQL database dump complete
--

\unrestrict 8VP4XK4NmuDHBBOD8vtZ0y4pPj9e4TRBL3CBiWiLd6rGbbLgKXZiAGDLxF6ZJ94

