# Generated by Django 6.0.7 on 2026-07-27 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaCliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('ruc', models.CharField(max_length=13)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.TextField()),
                ('logo', models.FileField(blank=True, null=True, upload_to='logos_empresas/')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('plan', models.CharField(choices=[('basico', 'Básico'), ('profesional', 'Profesional'), ('empresarial', 'Empresarial')], default='basico', max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalaReunion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad', models.PositiveIntegerField()),
                ('metros_cuadrados', models.DecimalField(decimal_places=2, max_digits=6)),
                ('piso', models.PositiveIntegerField()),
                ('foto', models.FileField(blank=True, null=True, upload_to='salas/')),
                ('precio_hora', models.DecimalField(decimal_places=2, max_digits=8)),
                ('equipamiento', models.CharField(choices=[('basico', 'Básico (Mesa y Sillas)'), ('ejecutivo', 'Ejecutivo (+ Proyector)'), ('premium', 'Premium (+ TV, Videoconferencia)')], default='basico', max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_factura', models.CharField(max_length=20, unique=True)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='facturas/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('tipo_factura', models.CharField(choices=[('mensual', 'Mensualidad'), ('reservas', 'Reservas de Salas'), ('evento', 'Evento'), ('otros', 'Otros Servicios')], default='mensual', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='reservas.empresacliente')),
            ],
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('foto', models.FileField(blank=True, null=True, upload_to='fotos_miembros/')),
                ('cargo', models.CharField(choices=[('gerente', 'Gerente'), ('empleado', 'Empleado'), ('freelancer', 'Freelancer')], default='empleado', max_length=20)),
                ('fecha_ingreso', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='reservas.empresacliente')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EscritorioDedicado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('piso', models.PositiveIntegerField()),
                ('posicion_x', models.PositiveIntegerField(default=0)),
                ('posicion_y', models.PositiveIntegerField(default=0)),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tipo', models.CharField(choices=[('individual', 'Individual'), ('compartido', 'Compartido'), ('privado', 'Privado')], default='individual', max_length=20)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('mantenimiento', 'Mantenimiento')], default='disponible', max_length=20)),
                ('miembro_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escritorios', to='reservas.miembro')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaSala',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('proposito', models.CharField(max_length=200)),
                ('numero_asistentes', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='confirmada', max_length=20)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_salas', to='reservas.miembro')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reservas.salareunion')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_evento', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('capacidad_maxima', models.PositiveIntegerField()),
                ('foto', models.FileField(blank=True, null=True, upload_to='eventos/')),
                ('tipo_evento', models.CharField(choices=[('networking', 'Networking'), ('capacitacion', 'Capacitación'), ('conferencia', 'Conferencia'), ('social', 'Social')], default='networking', max_length=20)),
                ('publico', models.BooleanField(default=False)),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='reservas.empresacliente')),
                ('sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='reservas.salareunion')),
            ],
        ),
    ]
