# Generated by Django 6.0.7 on 2026-07-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escritoriodedicado',
            name='posicion_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='escritoriodedicado',
            name='posicion_y',
            field=models.IntegerField(default=0),
        ),
    ]
