# Generated by Django 5.2.16 on 2026-08-05 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_escritoriodedicado_posicion_fields_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escritoriodedicado',
            options={'ordering': ['piso', 'posicion']},
        ),
        migrations.AlterUniqueTogether(
            name='escritoriodedicado',
            unique_together={('piso', 'posicion')},
        ),
        migrations.AddField(
            model_name='escritoriodedicado',
            name='posicion',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='empresacliente',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='empresacliente',
            name='ruc',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='organizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='reservas.empresacliente'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='reservas.salareunion'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='reservas.empresacliente'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='cedula',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='miembros', to='reservas.empresacliente'),
        ),
        migrations.AlterField(
            model_name='reservasala',
            name='miembro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_salas', to='reservas.miembro'),
        ),
        migrations.AlterField(
            model_name='reservasala',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='reservas.salareunion'),
        ),
        migrations.RemoveField(
            model_name='escritoriodedicado',
            name='posicion_x',
        ),
        migrations.RemoveField(
            model_name='escritoriodedicado',
            name='posicion_y',
        ),
    ]
