# Generated by Django 5.2.16 on 2026-08-05 17:38

import django.db.models.deletion
from django.db import migrations, models


def add_posicion_field_and_constraints(apps, schema_editor):
    """
    Agrega el campo posicion y constraints de forma segura
    """
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            # Verificar si el campo posicion ya existe
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name='reservas_escritoriodedicado' 
                AND column_name='posicion';
            """)
            
            posicion_exists = cursor.fetchone() is not None
            
            # Si no existe, agregarlo
            if not posicion_exists:
                try:
                    cursor.execute("""
                        ALTER TABLE reservas_escritoriodedicado 
                        ADD COLUMN posicion integer DEFAULT 1;
                    """)
                except Exception:
                    pass
            
            # Eliminar columnas antiguas si existen
            for col in ['posicion_x', 'posicion_y']:
                cursor.execute(f"""
                    SELECT column_name 
                    FROM information_schema.columns 
                    WHERE table_name='reservas_escritoriodedicado' 
                    AND column_name='{col}';
                """)
                
                if cursor.fetchone() is not None:
                    try:
                        cursor.execute(f'ALTER TABLE reservas_escritoriodedicado DROP COLUMN {col};')
                    except Exception:
                        pass


def fix_duplicate_emails(apps, schema_editor):
    """
    Arregla emails duplicados antes de agregar constraint UNIQUE
    """
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            # Encontrar y arreglar duplicados en empresas
            cursor.execute("""
                UPDATE reservas_empresacliente 
                SET email = email || '_' || id::text
                WHERE id NOT IN (
                    SELECT MIN(id) 
                    FROM reservas_empresacliente 
                    GROUP BY email
                );
            """)
            
            # Encontrar y arreglar duplicados en miembros
            cursor.execute("""
                UPDATE reservas_miembro 
                SET email = email || '_' || id::text
                WHERE id NOT IN (
                    SELECT MIN(id) 
                    FROM reservas_miembro 
                    GROUP BY email
                );
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_escritoriodedicado_posicion_fields_unique'),
    ]

    operations = [
        # Agregar campo posicion y eliminar campos antiguos de forma segura
        migrations.RunPython(
            add_posicion_field_and_constraints,
            reverse_code=migrations.RunPython.noop,
        ),
        # Arreglar emails duplicados antes de agregar UNIQUE constraint
        migrations.RunPython(
            fix_duplicate_emails,
            reverse_code=migrations.RunPython.noop,
        ),
        # Cambios en otros modelos
        migrations.AlterField(
            model_name='empresacliente',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='empresacliente',
            name='ruc',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='organizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='reservas.empresacliente'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='reservas.salareunion'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='reservas.empresacliente'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='cedula',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='miembros', to='reservas.empresacliente'),
        ),
        migrations.AlterField(
            model_name='reservasala',
            name='miembro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_salas', to='reservas.miembro'),
        ),
        migrations.AlterField(
            model_name='reservasala',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='reservas.salareunion'),
        ),
    ]
