# Generated by Django 5.2.16 on 2026-08-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_remove_old_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escritoriodedicado',
            options={'ordering': ['piso', 'codigo']},
        ),
        migrations.AlterField(
            model_name='escritoriodedicado',
            name='posicion',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
